# Site settings
title: Your awesome title
email: matdyer@gmail.com
description:
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://matthewAURA.github.io" # the base hostname & protocol for your site
twitter_username: blatantlynz
github_username:  matthewAURA

# Build settings
markdown: kramdown
